export enum UnidadesDeMedidas {
    CAIXA = 'CAIXA',
    DUZIA = 'DUZIA',
    FARDO = 'FARDO',
    FRASCO = 'FRASCO',
    GARRAFA = 'GARRAFA',
    GRAMA = 'GRAMA',
    KIT = 'KIT',
    LATA = 'LATA',
    LITRO = 'LITRO',
    MILIGRAMA = 'MILIGRAMA',
    MILILITRO = 'MILILITRO',
    PACOTE = 'PACOTE',
    PAR = 'PAR',
    QUILOGRAMA = 'QUILOGRAMA',
    ROLO = 'ROLO',
    SACHE = 'SACHE',
    UNIDADE = 'UNIDADE',
    OUTROS = 'OUTROS'
}