export const UnidadeDeMedida = [
    {value: 'UNIDADE', label: 'unidade'},
    {value: 'DUZIA', label: 'dúzia'},
    {value: 'QUILOGRAMA', label: 'quilograma'},
    {value: 'GRAMA', label: 'grama'},
    {value: 'MILIGRAMA', label: 'miligrama'},
    {value: 'LITRO', label: 'litro'},
    {value: 'MILILITRO', label: 'mililitro'},
    {value: 'PACOTE', label: 'pacote'},
    {value: 'CAIXA', label: 'caixa'},
    {value: 'FRASCO', label: 'frasco'},
    {value: 'GARRAFA', label: 'garrafa'},
    {value: 'LATA', label: 'lata'},
    {value: 'SACHE', label: 'sachê'},
    {value: 'ROLO', label: 'rolo'},
    {value: 'PAR', label: 'par'},
    {value: 'KIT', label: 'kit'},
    {value: 'FARDO', label: 'fardo'},
    {value: 'OUTROS', label: 'outros'},
];
